# This is a basic workflow to help you get started with Actions

name: Comment Workflow

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          # The message to print.
          message: Hello Comment successful
          repo-token: ${{ secrets.GH_TOKEN }}
          # Allow messages to be repeated.
          allow-repeats: false
