# This is a basic workflow to help you get started with Actions

name: Comment Workflow

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  latest-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GH_TOKEN }}
          exclude_types: "draft|prerelease"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"


  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: Comment Added successfully
          repo-token: ${{ secrets.GH_TOKEN }}
          allow-repeats: false
